[package]
name = "grrs"
version = "0.1.0"
authors = ["Jacinto Mba Cantero <j.mba@kentech-sp.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.2.18"
failure = "0.1.5"
exitfailure = "0.5.1"
